<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="ITCELL-DEV50" failures="1" tests="3" name="Login" time="10.669" errors="0" timestamp="2025-01-24T11:25:14 IST">
  <testcase classname="tests.TC_VALID_LOGIN" name="Login with valid credentials" time="2.071">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.TC_VALID_LOGIN.loginTest(TC_VALID_LOGIN.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Login with valid credentials -->
  <testcase classname="tests.TC_INVALID_PASSWORD" name="Invalid password" time="0.347"/>
  <testcase classname="tests.TC_INVALID_USERNAME" name="Invalid Username" time="0.403"/>
  <testcase classname="tests.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="tests.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="tests.BaseTest" name="@AfterSuite wrapUp" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite wrapUp -->
  <testcase classname="tests.BaseTest" name="@AfterSuite wrapUp" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite wrapUp -->
</testsuite> <!-- Login -->
